import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/Components/Header";
import { AuthProvider } from "@/context/authcontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CrypToo ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header isLogged={true} />
          <Toaster position="bottom-center" reverseOrder={false} />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
