import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/Components/Header";
import { AuthProvider } from "@/context/authcontext";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CrypToo ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header isLogged={true} />
          <Toaster position="bottom-center" reverseOrder={false} />
          {children}
        </AuthProvider>
        <Script src="https://unpkg.com/flowbite@1.4.7/dist/flowbite.js" />
        <Script src="https://buttons.github.io/buttons.js" />
        <Script src="https://demo.themesberg.com/windster/app.bundle.js" />
      </body>
    </html>
  );
}
